services:
  app:
    build: .
    container_name: cab_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=CABS
      - DB_USER=root
      - DB_PASSWORD=rootpassword
    stdin_open: true
    tty: true
    command: sh -c "./wait-for-db.sh && java -cp '.:lib/*:bin' services.MainApplication"

  db:
    image: mysql:8.0
    container_name: cab_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=CABS
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/scripts:/docker-entrypoint-initdb.d

volumes:
  db_data: