name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'docs/**'
      - 'config.properties'
      - 'SQLSetup.sh'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'docs/**'
      - 'config.properties'
      - 'SQLSetup.sh'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set execute permission for build.sh
        run: chmod +x build.sh

      - name: Run build.sh
        run: ./build.sh
